### ISSUE TITLE
Update pyproject.toml because coverage 5.0 has been released

### ISSUE THREAD

**Issue by jlubken** [pennsignals/dsdk#28]
Move coverage configuration from `setup.cfg` to `pyproject.toml`.

See feature here: https://github.com/nedbat/coveragepy/issues/664

Figure out how to represent `exclude_lines` in the toml file, because toml has a structured syntax unlike `setup.cfg`.

**Comment by djesic** [comment]
Came across this issue while looking for a solution myself.
This worked for me:
```
[tool.coverage.report]
exclude_lines = [
  "raise NotImplementedError",
  "def __repr__",
  "if __name__ == .__main__.:",
]
```

**Comment by jlubken** [comment]
Thanks! Updated in branch `add/api`.

**Comment by jlubken** [comment]
Completed.
