### ISSUE TITLE
Store datetimes as epoch time in mongo

### ISSUE THREAD

**Issue by mdbecker** [pennsignals/dsdk#36]
Store assert_on datetime as epoch time in mongo

    Utility functions for dsdk users to return the correct epoch time for storage in a db (milestone 1)

`time.time_ns()` seems like a good candidate.

Also store that batch at the end of the pipeline instead of the beginning. This will require us to get an OID from mongo at the beginning of the pipeline and use it again later. The assertion_time

**Comment by jlubken** [comment]
Removing mongo instead :-)
