### ISSUE TITLE
cookiecutter template for new projects

### ISSUE THREAD

**Issue by mdbecker** [pennsignals/dsdk#4]
Get the cdisepsis project into a good state and then use it to make a cookiecutter template for future projects. Some things that would be good to address before we do this:
 * Get rid of tox, replace with pytest
   * Or not... we might want to keep tox to manage our environments.
 * Make sure versioning works as expected (seems broken now)
 * Verify CICD works
 * Provide separate dockerfiles for testing vs deployment
 * Update the readme with steps required to get the project in a working state and how to use it

**Comment by jlubken** [comment]
Use the template instead.
