### ISSUE TITLE
Add caching for df_from_query

### ISSUE THREAD

**Issue by jlubken** [pennsignals/dsdk#67]
The generates sql is currently written to a temp file.

Checksum this file along with the host of the db connection to rapidly return results for what should be the same query.

Cache with something durable against datatype rot (no json). (pickle the dataframe. See if we can compress pickle at all)

**Comment by GrayEye** [comment]
We will want to hash the rendered sql and pairing it with resulting dataframe 
Hashed_Name_64 = base64(hash(rendered))
if Hashed_Name_64 not in temp dir:
dataframe = execute(rendered)
pickledDF = pickle(dataframe) 
write PickledDF to Hashed_Name_64
else
read PickledDF from file
unpickle pickledDF
