### ISSUE TITLE
Pass in start time into dsdk

### ISSUE THREAD

**Issue by mdbecker** [pennsignals/dsdk#7]
Rather then depend on `datetime.utcnow`, pass this into the application via some other mechanism (commandline arguments?) to assist in supporting replay.

**Comment by mdbecker** [comment]
To further support replay we need to also store asserted on and valid on times in the evidence and we also need to ensure application queries are always bounded on both ends (right and left sides).

**Comment by jlubken** [comment]
Discuss acquiring "now" from the leading ragged edge of time for each data stream, and an appropriate project to implement this feature.

**Comment by jlubken** [comment]
AS_OF and TIME_ZONE added to dsdk. If not supllied they are retrieved from the database clock as the single authoritative source for the time zone and utc now.
